name:                os-string-compat
version:             1.0.0
github:              "Anteproperispomenon/os-string-compat"
license:             BSD-3-Clause
author:              "David Wilson"
# maintainer:        "example@example.com"
copyright:           "2025 David Wilson"

extra-source-files:
- README.md
- src/System/OsString/include/Common.hs
- test/bytestring/Properties/include/Common.hs

extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Compatibility layer for os-string
category:            System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Anteproperispomenon/os-string-compat#readme>

default-extensions:
- ImportQualifiedPost
- LambdaCase
- MultiWayIf
- OverloadedStrings
- PackageImports
- ScopedTypeVariables
- TupleSections
- TypeApplications

dependencies:
- base >= 4.14 && < 5
- os-string >= 2.0.1 && <= 2.1
- filepath >= 1.4.101.0 && <= 1.6
- bytestring >= 0.11.3.0 && < 0.13
- exceptions >= 0.10.5 && < 0.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

tested-with:
  - GHC == 9.2.8 || == 9.8.4 || == 9.10.3 || == 9.12.2

library:
  source-dirs: src

# executables:
#   os-string-compat-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - os-string-compat

tests:
  bytestring-tests:
    main:                Spec.hs
    source-dirs:         
      - test 
      - test/bytestring
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - os-string-compat
    - bytestring  >=0.11.3.0 && < 0.13
    - QuickCheck  >=2.7 && <2.20

  encoding-tests:
    main:                Spec.hs
    source-dirs:         
      - test 
      - test/encoding
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - os-string-compat
    - bytestring  >=0.11.3.0
    - deepseq >= 1.4.8 && < 1.6
    - QuickCheck  >=2.7 && <2.20
    - quickcheck-classes-base ^>=0.6.2

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options: 
      - -O2 
      # - -O1
      - "-with-rtsopts=-A32m" 
    when:
      - condition: impl(ghc >= 8.6)
        ghc-options: -fproc-alignment=64
    dependencies:
      - os-string-compat
      - bytestring >= 0.11.3.0 && < 0.13
      - deepseq >= 1.4.8 && < 1.6
      - tasty-bench >= 0.4 && < 0.5
      - random >= 1.2.1.3 && < 1.4
  